name: Changelog

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: ✨ Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
      - name: 🚚 Restore
        run: dotnet restore "dev/ChangelogPageMaker"
      - name: 🛠️ Build
        run: dotnet build "dev/ChangelogPageMaker" --configuration Release --no-restore
      - name: 🧪 Test
        run: dotnet test "dev/ChangelogPageMaker" --no-restore --verbosity minimal
      - name: 🧐 Inspect Changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: ✅ Commit Changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git add static/images/contributors/*.*
          git commit -am "Changelog: Automated Update"
          git push
          git status
